/// <autosync enabled="true" />
/// <reference path="../client scripts/mvcfoolproof.unobtrusive.min.js" />
/// <reference path="../client scripts/mvcfoolproofjqueryvalidation.min.js" />
/// <reference path="../client scripts/mvcfoolproofvalidation.min.js" />
/// <reference path="bootstrap.js" />
/// <reference path="custom/deal.js" />
/// <reference path="custom/details.js" />
/// <reference path="custom/numeric.js" />
/// <reference path="custom/search.js" />
/// <reference path="custom/site.js" />
/// <reference path="foolproof/mvcfoolproof.unobtrusive.js" />
/// <reference path="foolproof/MvcFoolproofJQueryValidation.js" />
/// <reference path="foolproof/MvcFoolproofValidation.js" />
/// <reference path="jquery.are-you-sure.js" />
/// <reference path="jquery.bpopup.min.js" />
/// <reference path="jquery.dirrty.js" />
/// <reference path="jquery.dirtyforms.min.js" />
/// <reference path="jquery.maskedinput.min.js" />
/// <reference path="jquery.ui.table.js" />
/// <reference path="jquery.unobtrusive-ajax.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-3.1.0.js" />
/// <reference path="jquery-3.1.0.slim.js" />
/// <reference path="jquery-3.1.1.js" />
/// <reference path="jquery-3.1.1.slim.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="modernizr-2.8.3.js" />
/// <reference path="respond.js" />
/// <reference path="respond.matchmedia.addlistener.js" />
/// <reference path="select2.min.js" />
/// <reference path="toastr.js" />
